### ISSUE TITLE
Yaml2Csv.convert returns csv with last column blank

### ISSUE THREAD

**Issue by spanuska** [buru/locales_export_import#3]
This is such a useful tool - thanks for making it! I am having one problem, though, and I'm not seeing an obvious reason.

When I call `LocalesExportImport::Yaml2Csv.convert(['es.yml, fr.yml, it.yml, de.yml'], 'output.csv')`, `output.csv` will have a column for "de_value", but all the rows are blank (whereas the actual file is not). When I change the order of the filenames in the array, the last one is always blank, but the files that do get converted are converted correctly.

**Comment by spanuska** [comment]
Nevermind this - the issue was a typo on my end 😳

**Comment by buru** [comment]
Hello! From the first comment I see you've forgot to close the matching '-s, right?

No problem, good that it was not a bug. Thank you for feedback!

**Comment by spanuska** [comment]
Ha, that was just a typo in my comment, but good catch. (fixed now)

Actually, you might be interested in this behavior. The typo was a mismatch in keys: en.yml has a key called `assistance` and de.yml had the key misspelled - `assitance`. As it is now, I believe this program uses the first file's keys as the keys to match. Not sure if there'd be a use case for wanting to grab any additional keys from the other files....but perhaps an addition for the future.

Thanks again!
